"""
Strategy selection module.
"""

from typing import Dict, Any

from ..core.models import Conflict, AnalysisResult, ResolutionStrategy, RiskLevel
from ..utils.logger import get_logger

logger = get_logger(__name__)


class StrategySelector:
    """
    Selects the appropriate resolution strategy based on analysis.
    """

    def select_strategy(
        self,
        conflict: Conflict,
        analysis: AnalysisResult,
        context: Dict[str, Any] = None,
    ) -> ResolutionStrategy:
        """
        Select the best resolution strategy.
        """
        logger.info("Selecting strategy", conflict_id=conflict.id, risk=analysis.risk_level)

        # 1. Critical/High Risk -> Manual
        if analysis.risk_level in [RiskLevel.CRITICAL, RiskLevel.HIGH]:
            return self._create_manual_strategy(
                conflict, "High risk conflict requires manual resolution."
            )

        # 2. Constitutional Violations -> Manual (or specific fix)
        if analysis.constitutional_violations:
            return self._create_manual_strategy(
                conflict,
                f"Constitutional violations detected: "
                f"{', '.join(analysis.constitutional_violations)}",
            )

        # 3. Auto-resolvable -> Automated Strategy
        if analysis.is_auto_resolvable:
            if analysis.recommended_strategy_type == "union":
                return ResolutionStrategy(
                    id=f"strat-union-{conflict.id}",
                    name="Union Merge",
                    description="Combine changes from both branches (e.g. imports)",
                    steps=[],  # Steps would be generated by generator
                    confidence_score=0.9,
                    risk_level=RiskLevel.LOW,
                    requires_approval=False,
                    type="union",
                )
            elif analysis.recommended_strategy_type == "accept_incoming":
                return ResolutionStrategy(
                    id=f"strat-incoming-{conflict.id}",
                    name="Accept Incoming",
                    description="Accept changes from the incoming branch",
                    steps=[],
                    confidence_score=0.95,
                    risk_level=RiskLevel.LOW,
                    requires_approval=False,
                    type="accept_incoming",
                )
            elif analysis.recommended_strategy_type == "automated":
                return ResolutionStrategy(
                    id=f"strat-auto-{conflict.id}",
                    name="Automated Semantic Merge",
                    description="Automatically resolve using semantic analysis",
                    steps=[],
                    confidence_score=0.9,
                    risk_level=RiskLevel.LOW,
                    requires_approval=False,
                    type="automated",
                )

        # Default -> Manual
        return self._create_manual_strategy(
            conflict, "Complex conflict requires manual resolution."
        )

    def _create_manual_strategy(self, conflict: Conflict, reason: str) -> ResolutionStrategy:
        return ResolutionStrategy(
            id=f"strat-manual-{conflict.id}",
            name="Manual Resolution",
            description=f"Manual intervention required. Reason: {reason}",
            steps=[],
            confidence_score=1.0,
            risk_level=RiskLevel.MEDIUM,
            requires_approval=True,
            type="manual",
        )
