    conditions:
pull_request_rules:
  - name: Ping PR author when conflicting
    description: Warn the pull request author when their PR are conflicting
    conditions:
      - conflict
      - -closed
    actions:
      comment:
        message: >
          👋 @{{author}} your PR is conflicting and needs to be updated to be
          merged
  - name: Automatic merge during office hours + hotfix support
    description: Merge when PR passes all conditions. Hotfixes merge anytime, others during office hours. Must pass CI and reviews, not be draft or conflicting.
    conditions:
      - or:
          - schedule = Mon-Fri 09:00-17:00[America/Los_Angeles]
          - label = hotfix
      - check-success=test
      - "#approved-reviews-by>=1"
      - -conflict
      - -draft
    actions:
      merge:
  - name: Label conflicting pull requests
    description: Add a label to a pull request with conflict to spot it easily
    conditions:
      - conflict
      - -closed
    actions:
      label:
        toggle:
          - conflict
