import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    ignores: ['dist/*', 'build/*', 'node_modules/*', 'client/dist/*', 'client/build/*', 'client/node_modules/*', '.venv/*'],
    languageOptions: {
      globals: {
        browser: true,
        es2021: true,
        node: true,
        console: true,
        URL: true,
        fetch: true,
        Request: true,
        Response: true,
        Headers: true,
        DOMException: true,
        ReadableStream: true,
        window: true,
        document: true,
        navigator: true,
        localStorage: true,
        sessionStorage: true,
        setTimeout: true,
        clearTimeout: true,
        setInterval: true,
        clearInterval: true,
        Event: true,
        CustomEvent: true,
        AbortController: true,
        AbortSignal: true
      }
    },
    rules: {
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      'no-undef': 'off',
      'no-prototype-builtins': 'off',
      'no-useless-escape': 'off',
      'no-control-regex': 'off',
      'no-useless-assignment': 'off',
      'no-cond-assign': 'off',
      'no-case-declarations': 'off',
      'no-empty': 'off',
      'no-extra-boolean-cast': 'off',
      'no-async-promise-executor': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      'n/prefer-global/process': 'off',
      'no-unassigned-vars': 'off',
      'no-func-assign': 'off',
      'no-fallthrough': 'off',
      'no-self-assign': 'off',
      '@typescript-eslint/no-this-alias': 'off',
      'getter-return': 'off',
      'no-useless-catch': 'off',
      'no-unused-private-class-members': 'off',
      'no-redeclare': 'off',
      'no-sparse-arrays': 'off',
      'preserve-caught-error': 'off',
      'no-unsafe-finally': 'off',
      'no-constant-condition': 'off',
      'no-unsafe-optional-chaining': 'off',
      'no-irregular-whitespace': 'off',
      'no-unreachable': 'off',
      'no-misleading-character-class': 'off',
      '@typescript-eslint/no-array-constructor': 'off',
      'no-duplicate-case': 'off',
      'no-regex-spaces': 'off',
      'no-constant-binary-expression': 'off',
      'require-yield': 'off',
      'no-setter-return': 'off',
      'no-global-assign': 'off',
      'constructor-super': 'off'
    }
  }
);
