version: '3.8'

services:
  backend:
    command: uvicorn backend.python_backend.main:app --host 0.0.0.0 --port 8000
    # For production, consider using gunicorn with uvicorn workers
    # command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.python_backend.main:app --bind 0.0.0.0:8000

  frontend:
    build:
      target: final
    ports:
      - "80:80"