version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: deployment/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./models:/app/models
    environment:
      - PORT=8000
      - NLP_MODEL_DIR=/app/models
    # Add other environment variables as needed

  frontend:
    build:
      context: ../
      dockerfile: deployment/Dockerfile.frontend
    ports:
      - "5173:80"
    depends_on:
      - backend