version: '3.8'

services:
  backend:
    build:
      context: .. # Assuming context is the parent directory of 'deployment'
      dockerfile: deployment/Dockerfile.backend
      target: development # Default target stage
    depends_on: # Keep depends_on key, but remove postgres
      # postgres: # Removed as backend will use SQLite
      #   condition: service_healthy # Removed
    environment:
      # - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/emailintelligence # Commented out for SQLite
      # Other common environment variables can be added here
    volumes:
      - ../server:/app/server
      - ../shared:/app/shared

volumes:
  # postgres_data: # Removed as the postgres service is removed

networks:
  default:
    driver: bridge
