version: '3.8'

services:
  backend:
    command: uvicorn backend.python_backend.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../backend:/app/backend
      - ../models:/app/models

  frontend:
    build:
      target: builder
    volumes:
      - ../client:/app/client
      - /app/client/node_modules
    command: npm run dev