#!/bin/bash
# pause-current-task.sh - Quick task pause script

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🚀 Quick Task Pause Script${NC}"
echo "============================="

# Get current task ID from argument or user input
TASK_ID="$1"
if [ -z "$TASK_ID" ]; then
    echo -e "${YELLOW}Enter Task ID to pause:${NC} "
    read -r TASK_ID
fi

if [ -z "$TASK_ID" ]; then
    echo -e "${RED}❌ Error: Task ID required${NC}"
    echo "Usage: ./pause-current-task.sh <TASK_ID>"
    exit 1
fi

echo -e "${BLUE}Pausing task: $TASK_ID${NC}"

# Create timestamp for files
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
PAUSE_FILE="pause-log-${TASK_ID}-${TIMESTAMP}.md"

# Check git status
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo -e "${RED}❌ Not in a git repository${NC}"
    exit 1
fi

# Check if there are uncommitted changes
HAS_CHANGES=false
if [ -n "$(git status --porcelain)" ]; then
    HAS_CHANGES=true
fi

echo -e "${YELLOW}📊 Current Status:${NC}"
echo "  Working directory: $(pwd)"
echo "  Git branch: $(git branch --show-current)"
echo "  Modified files: $(git status --porcelain | wc -l)"
echo "  Uncommitted changes: $([ "$HAS_CHANGES" = true ] && echo "YES" || echo "NO")"

if [ "$HAS_CHANGES" = true ]; then
    echo -e "${YELLOW}⚠️  Committing current progress...${NC}"
    git add .
    
    # Generate commit message
    COMMIT_MSG="pause: checkpoint task $TASK_ID at $(date)
    
- Task: $TASK_ID
- Pause time: $(date +"%Y-%m-%d %H:%M:%S")
- Status: Ready for resume
- Files modified: $(git status --porcelain | wc -l)
- Branch: $(git branch --show-current)

See $PAUSE_FILE for detailed resume information."
    
    git commit -m "$COMMIT_MSG"
    echo -e "${GREEN}✅ Committed progress${NC}"
else
    echo -e "${GREEN}✅ Working directory clean${NC}"
fi

# Create detailed pause log
cat > "$PAUSE_FILE" << EOF
# Task Pause Log: $TASK_ID

## Metadata
- **Task ID**: $TASK_ID
- **Pause Time**: $(date)
- **Timestamp**: $TIMESTAMP
- **Working Directory**: $(pwd)
- **Git Branch**: $(git branch --show-current)
- **Last Commit**: $(git log -1 --oneline)

## Quick Status
- **Status**: IN PROGRESS (Paused)
- **Files Modified**: $(git status --porcelain | wc -l)
- **Changes**: $([ "$HAS_CHANGES" = true ] && echo "Committed to git" || echo "None - clean state")

## Recent Activity
$(git log --oneline -5)

## Current Changes
$(git status --short)

## Resume Instructions

### 1. Quick Resume
\`\`\`bash
# Check current state
git status

# View pause details
cat $PAUSE_FILE

# Resume task
# [Add your specific resume commands here]
\`\`\`

### 2. Resume with TaskMaster
\`\`\`bash
# Update task status
task-master set-status --id=$TASK_ID --status=in-progress

# Add progress note
task-master update-subtask --id=$TASK_ID --prompt="RESUMING: [what you need to continue]

Last pause: $(date)
Progress: $[ "$HAS_CHANGES" = true ] && echo "Progress committed" || echo "Clean state"
Next steps: [add your next steps]"
\`\`\`

### 3. Development Resume
\`\`\`bash
# Resume development work
# [Add your specific development commands]
\`\`\`

## Next Actions
1. Review pause log and current git state
2. Continue from exact pause point  
3. Test functionality before proceeding
4. Update TaskMaster when complete

---
Generated by pause-current-task.sh on $(date)
EOF

echo -e "${GREEN}📄 Created pause log: $PAUSE_FILE${NC}"

# Create quick resume script
RESUME_SCRIPT="resume-${TASK_ID}.sh"
cat > "$RESUME_SCRIPT" << EOF
#!/bin/bash
# Resume script for task $TASK_ID

echo "🔄 Resuming task: $TASK_ID"
echo "📄 Pause details:"
cat "$PAUSE_FILE"

# Check git status
echo -e "\n📊 Current Status:"
git status --short

echo -e "\n🎯 Next Steps:"
echo "1. Review the pause details above"
echo "2. Update TaskMaster status (if needed)"
echo "3. Continue development work"
echo "4. Update progress as you go"

# Optionally update TaskMaster
echo -e "\n🤖 TaskMaster Integration:"
echo "Update status: task-master set-status --id=$TASK_ID --status=in-progress"
echo "Add progress: task-master update-subtask --id=$TASK_ID --prompt=\"RESUMING: [your next steps]\""
EOF

chmod +x "$RESUME_SCRIPT"

echo -e "${GREEN}🎯 Next Steps:${NC}"
echo "1. ✅ Progress saved to git"
echo "2. ✅ Pause log created: $PAUSE_FILE"
echo "3. ✅ Resume script created: $RESUME_SCRIPT"
echo "4. 🔄 To resume: ./$RESUME_SCRIPT"

if command -v task-master >/dev/null 2>&1; then
    echo -e "\n🤖 Optional TaskMaster Update:"
    echo "task-master set-status --id=$TASK_ID --status=in-progress"
    echo "task-master update-subtask --id=$TASK_ID --prompt=\"PAUSED: Resume from $(date)\""
fi

echo -e "\n${GREEN}🎉 Task $TASK_ID paused successfully!${NC}"