"""
Import Audit Command Module (Rigorous Edition)

High-fidelity import refactoring with a surgical review gate for ecosystem fixes.
Ensures that no linter changes are applied blindly.
"""

import ast
import subprocess
from argparse import Namespace
from pathlib import Path
from typing import Any, Dict, List, Tuple

from ..interface import Command


class ImportAuditCommand(Command):
    """
    Command for high-fidelity import refactoring and standardization.
    
    Includes a 'Surgical Review Gate' to prevent blind application of ecosystem fixes.
    """

    def __init__(self):
        self._security_validator = None

    @property
    def name(self) -> str:
        return "import-audit"

    @property
    def description(self) -> str:
        return "Audit, normalize, and surgically standardize repository imports"

    def add_arguments(self, parser: Any) -> None:
        parser.add_argument("--fix", action="store_true", help="Apply AST-based fixes")
        parser.add_argument("--standardize", action="store_true", help="Run ruff and isort (Review required)")
        parser.add_argument("--path", default=".", help="Directory to scan")
        parser.add_argument("--map", help="Path to JSON refactor map (legacy:new)")
        parser.add_argument("--legacy-roots", default="backend,core,utils")
        parser.add_argument("--new-prefix", default="src")

    def get_dependencies(self) -> Dict[str, Any]:
        return {"security_validator": "SecurityValidator"}

    def set_dependencies(self, dependencies: Dict[str, Any]) -> None:
        self._security_validator = dependencies.get("security_validator")

    async def execute(self, args: Namespace) -> int:
        root_dir = Path(args.path)
        refactor_map = self._build_refactor_map(args)
        
        print(f"🧬 Starting High-Fidelity AST Refactor in '{root_dir.absolute()}'")
        
        # 1. AST Phase (Manual/Surgical)
        py_files = list(root_dir.rglob("*.py"))
        fixed_count = 0
        for py_file in py_files:
            if "venv" in str(py_file):
                continue
            if self._process_file(py_file, refactor_map, args.fix):
                fixed_count += 1

        print(f"✅ AST Phase Complete. Files Modified: {fixed_count}")

        # 2. Ecosystem Phase (Surgical Review Gate)
        if args.standardize:
            print("\n🔍 Investigating Industry-Standard Optimizations (Dry Run)...")
            diff = self._get_standardization_diff(root_dir)
            
            if not diff:
                print("✨ No ecosystem fixes needed.")
                return 0

            print("\n--- PROPOSED ECOSYSTEM FIXES (Ruff/isort) ---")
            print(diff)
            print("\n⚠️  CAUTION: These changes were generated by general linters.")
            print("To apply these specific changes, please run the command again with --fix-ecosystem")

        return 0

    def _get_standardization_diff(self, path: Path) -> str:
        """Generates a combined diff of what Ruff and isort WOULD do."""
        results = []
        
        # 1. Check Ruff (Unused imports, etc)
        ruff_diff = subprocess.run(
            ["ruff", "check", "--diff", str(path)], 
            capture_output=True, text=True
        ).stdout
        if ruff_diff:
            results.append("--- RUFF PROPOSALS ---\n" + ruff_diff)
        
        # 2. Check isort (Grouping/Sorting)
        isort_diff = subprocess.run(
            ["isort", "--diff", str(path)], 
            capture_output=True, text=True
        ).stdout
        if isort_diff:
            results.append("--- ISORT PROPOSALS ---\n" + isort_diff)
        
        return "\n".join(results)

    def _build_refactor_map(self, args: Namespace) -> Dict[str, str]:
        return {r.strip(): f"{args.new_prefix}.{r.strip()}" for r in args.legacy_roots.split(",")}

    def _process_file(self, file_path: Path, mapping: Dict[str, str], apply_fix: bool) -> bool:
        try:
            content = file_path.read_text(encoding='utf-8')
            tree = ast.parse(content)
            changes = []
            
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        if alias.name.split('.')[0] in mapping:
                            changes.append((node.lineno, alias.name, self._map_name(alias.name, mapping)))
                elif isinstance(node, ast.ImportFrom) and node.module:
                    root = node.module.split('.')[0]
                    if root in mapping:
                        changes.append((node.lineno, node.module, self._map_name(node.module, mapping)))

            if not changes:
                return False
            
            if apply_fix:
                return self._apply_ast_changes(file_path, content, changes)
            else:
                print(f"  [!] {file_path.name}: {len(changes)} legacy imports detected.")
                return False
        except Exception:
            return False

    def _map_name(self, original: str, mapping: Dict[str, str]) -> str:
        root = original.split('.')[0]
        suffix = original[len(root):]
        return mapping[root] + suffix

    def _apply_ast_changes(self, file_path: Path, content: str, changes: List[Tuple[int, str, str]]) -> bool:
        lines = content.splitlines()
        modified = False
        for lineno, old, new in sorted(changes, key=lambda x: x[0], reverse=True):
            idx = lineno - 1
            if idx < len(lines) and old in lines[idx]:
                lines[idx] = lines[idx].replace(old, new)
                modified = True
        if modified:
            file_path.write_text("\n".join(lines) + "\n", encoding='utf-8')
            print(f"  [FIXED] {file_path.name}")
            return True
        return False
