name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.mergeable_state == 'clean' && !github.event.pull_request.draft
    
    steps:
      - name: Wait for CI checks to complete
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-ci
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: test
          ref: ${{ github.event.pull_request.head.sha }}
          timeoutSeconds: 600
          intervalSeconds: 10
        
      - name: Auto-merge Dependabot PR
        if: steps.wait-for-ci.outputs.conclusion == 'success'
        run: |
          set -e
          echo "CI checks passed. Auto-merging Dependabot PR #${{ github.event.pull_request.number }}"
          
          # Approve the PR first
          if ! gh pr review ${{ github.event.pull_request.number }} --approve --body "✅ CI checks passed! Auto-merging this Dependabot PR."; then
            echo "Failed to approve PR. Exiting."
            exit 1
          fi
          
          # Enable auto-merge
          if ! gh pr merge --auto --merge ${{ github.event.pull_request.number }}; then
            echo "Failed to enable auto-merge. Checking if already enabled..."
            # Check if auto-merge is already enabled
            if gh pr view ${{ github.event.pull_request.number }} --json autoMergeRequest --jq '.autoMergeRequest' | grep -q "null"; then
              echo "Auto-merge failed and is not enabled. Manual intervention required."
              exit 1
            else
              echo "Auto-merge is already enabled."
            fi
          fi
          
          echo "Auto-merge successfully enabled for PR #${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}